config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users, only: [:edit, :update]
  resources :groups, only: [:new, :create, :edit, :update] do
    resources :messages, only: [:index,:create]
  end
  root "groups#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/group.rb
class Group < ApplicationRecord
  has_many :group_users
  has_many :users, through: :group_users
  has_many :messages
  
  validates :name, presence: true

  def show_last_message
    if (last_message = messages.last).present?
      last_message.content? ? last_message.content : '画像が投稿されています'
    else
      'まだメッセージはありません。'
    end
  end

end

app/models/group_user.rb
class GroupUser < ApplicationRecord
  belongs_to :group
  belongs_to :user
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :group
  belongs_to :user

  # unless：条件に一致しない場合のみばりテーション実行
  validates :content, presence: true, unless: :image?

  mount_uploader :image, ImageUploader
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  has_many :messages
  has_many :group_users
  has_many :groups, through: :group_users
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!  
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :set_group, only: [:edit, :update]
  
  def index
  end
  
  def new
    @group = Group.new
    @group.users << current_user
  end

  def create
    @group = Group.new(group_params)
    if @group.save
      redirect_to root_path, notice: 'グループを作成しました'
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @group.update(group_params)
      redirect_to group_messages_path(@group), notice: 'グループを編集しました'
    else
      render :edit
    end
  end

  private
  def group_params
    params.require(:group).permit(:name, {:user_ids => []})
  end
  
  def set_group
    @group = Group.find(params[:id])
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  def index
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def edit
  end 

  def update
    if current_user.update(user_params)
      redirect_to root_path
    else
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/groups/_form.html.haml
= form_for group do |f|
  - if group.errors.any?
    .chat-group-form__errors
      %h2= "#{group.errors.full_messages.count}件のエラーが発生しました。"
      %ul
        - group.errors.full_messages.each do |message|
          %li= message
  .chat-group-form__field
    .chat-group-form__field--left
      = f.label :name, class: 'chat-group-form__label'
    .chat-group-form__field--right
      = f.text_field :name, class: 'chat__group_name chat-group-form__input', placeholder: 'グループ名を入力してください'
  .chat-group-form__field.clearfix
    / この部分はインクリメンタルサーチ（ユーザー追加の非同期化のときに使用します
    /
      <div class='chat-group-form__field--left'>
      <label class="chat-group-form__label" for="chat_group_チャットメンバーを追加">チャットメンバーを追加</label>
      </div>
      <div class='chat-group-form__field--right'>
      <div class='chat-group-form__search clearfix'>
      <input class='chat-group-form__input' id='user-search-field' placeholder='追加したいユーザー名を入力してください' type='text'>
      </div>
      <div id='user-search-result'></div>
      </div>
  .chat-group-form__field.clearfix
    .chat-group-form__field--left
      %label.chat-group-form__label{:for => "chat_group_チャットメンバー"} チャットメンバー
    .chat-group-form__field--right
      / グループ作成機能の追加時はここにcollection_check_boxesの記述を入れてください
      = f.collection_check_boxes :user_ids, User.all, :id, :name
      / この部分はインクリメンタルサーチ（ユーザー追加の非同期化のときに使用します
      /
        <div id='chat-group-users'>
        <div class='chat-group-user clearfix' id='chat-group-user-22'>
        <input name='chat_group[user_ids][]' type='hidden' value='22'>
        <p class='chat-group-user__name'>seo_kyohei</p>
        </div>
        </div>
  .chat-group-form__field.clearfix
    .chat-group-form__field--left
    .chat-group-form__field--right
      = f.submit class: 'chat-group-form__action-btn'

app/views/groups/edit.html.haml
.chat-group-form
  %h チャットグループ編集
  = render partial: 'form', locals: {group: @group}

app/views/groups/index.html.haml
.wrapper

  = render '/layouts/shared/chat-side'

app/views/groups/new.html.haml
.chat-group-form
  %h 新規チャットグループ
  = render partial: 'form', locals: {group: @group}

app/views/layouts/_notifications.html.haml
.notification
  - flash.each do |key, value|
    = content_tag :div, value, class: key

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title ChatSpace
    = csrf_meta_tags
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    = render 'layouts/notifications'
    = yield

app/views/layouts/shared/_chat-side.html.haml
.chat-side
  .side-headder
    .side-headder__box
      %p.side-headder__box__name
        = current_user.name 
      %ul.side-headder__box__user-menu
        %li.side-headder__box__user-menu__icon
          =link_to new_group_path do
            %i.fa.fa-edit
        %li.side-headder__box__user-menu__icon
          =link_to edit_user_path(current_user) do
            %i.fa.fa-cog
  .groups
    .group
      - current_user.groups.each do |group|
        = link_to group_messages_path(group) do
          .group__name
            = group.name
          .group__message
            = group.show_last_message

app/views/messages/_message.html.haml
.message
  .message__uper-info
    .message__uper-info__talker
      = message.user.name
    .message__uper-info__date
      = message.created_at.strftime("%Y/%m/%d %H:%M")
  %p.message__text
    - if message.content.present?
      %p.lower-message__content
        = message.content
    = image_tag message.image.url, class: 'lower-message__image' if message.image.present?

app/views/messages/index.html.haml
.flash-box
.wapper
  .chat-side
    .side-headder
      .side-headder__box
        %p.side-headder__box__name ss 
        %ul.side-headder__box__user-menu
          %li.side-headder__box__user-menu__icon
            =link_to root_path do
              %i.fa.fa-edit
          %li.side-headder__box__user-menu__icon
            =link_to root_path do
              %i.fa.fa-cog
    .groups
      %a
        =link_to root_path do
          .group
            %p.group__name みそ
            %p.group__message 大豆と塩
  .chat-main
    .main-headder
      .current-group
        %h2.current-group__name
          pp
        %ul.member-list 
          Member : 
          %li.member-list__member rr
          %li.member-list__member oo
      %a{:href => '/'}
        .main-headder__edit-btn Edit
    .messages
      .message
        .message__uper-info
          .message__uper-info__talker qq
          .message__uper-info__date 20190202
        %p.message__text 作り方
    .form
      %form.new-message#new-message{:enctype => "multipart/form-data", :action => "/", :accept-charset => "UTF-8", :method => "post"}
        %input{:name => "utf8", :type => "hidden", :value => "✔︎"}
        %input{:type => "hidden", :name => "authenticity", :value => "01AaSVZIMCk2VDP2VOQd+AlH5VA6Gj62OP7jxWJNwi570HkHdBf+7JQogFKKZZcF+zUYwJ1RciyCvD8KGTvl+w=="}
        .input-box
          %input.input-box__text{:placeholder => "type a message", :type => "text", :name => "message[content]"}
          %label.input-box__image{:for => "massage_image"}
            %i.fa.fa-image
            %input.input-box__image__file#message_image{:type => "file", :name => "message[image]"}
        %input.submit-btn{:type => "submit", :name => "commit", :value =>"Send", :data-disable-with => "Send"}

app/views/users/edit.html.haml
#account-page.account-page
  .account-page__inner.clearfix
    .account-page__inner--left.account-page__header
      %h2 Edit Account
      %h5 アカウントの編集
      = link_to "ログアウト", destroy_user_session_path, method: :delete, class: 'btn'
      = link_to "トップページに戻る", :back, class: 'btn'
    .account-page__inner--right.user-form
      = form_for(current_user) do |f|
        .field
          .field-label
            = f.label :name
          .field-input
            = f.text_field :name, autofocus: true
        .field
          .field-label
            = f.label :email
          .field-input
            = f.email_field :email
        .actions
          = f.submit "Update", class: 'btn'